console.log("Era uma vez...")
console.log("uma menina chamada Dina Fritz.")
console.log("Que caminhava pela estrada de tijolos amarelos.")
console.log("E um menino chamado Gohan.")
console.log("Gohan tinha cabelos espetados, mas não o lavava.")
console.log("Dina possuia cabelos dourados e olhos cinzas azulados.")
console.log("Eles viviam pacificamente dentro da Muralha Maria de tijolos de barro.")
console.log("com medo de Freeza.")
console.log("Dina ligou para Naruto dizendo que precisava de ajuda.")
console.log("O jovem Naruto veio da vila da folha e lhes ensinou a arte sábia ninja.")
console.log("Onde o Kakashi ensinava os alunos a dança do ventre preso.")
console.log("Mas encotrou o mestre Miagi e Daniel San treinando com")
console.log("Edivaldo Pericleiton Rasta, ao som do Cabeça de Gelo!")
console.log("Depois de ouvir muito seu som, o Cabeça de Gelo derreteu. Oh!")
console.log("Foi quando Goku apareceu e mostrou quem é que manda. ")
console.log("Mas Goku chamou seu amigo Saitama")
console.log("Saitama era o guerreio mais poderoso do universo.")
console.log("Apesar de ser o mais poderoso, tinha medo de borboletas")
console.log("E, por ironia do destino, seu principal inimigo era uma borboleta")
console.log("Durante a brutal batalha que acontece, do outro lado do planeta um meteoro cai.")
console.log("Mas, com toda a sua bravura, ele enfrenta a borboleta")
console.log("Porém, a borboleta vai para o seu reino pedir reforços")
console.log("Até que um o freeza manda um de seus capangas, o colossal pra invadir a Muralha Maria de tijolos de barro")
console.log("3 crianças estavam brincando de amarelinha enquanto mamãe fazia pipoca!")
console.log("Entretidos com a batalha, não perceberam a queda do meteoro que dizimou boa parte do planeta...")
console.log("Da mesma forma que aconteceu com os dinossauros")
console.log("A borboleta se chamava borbo life")