console.log("Era uma vez...")
console.log("uma menina chamada dina fritz")
console.log("que caminhava pela estrada de tijolos amarelos.")
console.log("e um menino chamado Gohan")
console.log("e Gohan tinha cabelos espetados.")
console.log("Dina possuia cabelos dourados e olhos cinzas")
console.log("Eles viviam pacificamente dentro da Muralha Maria")
console.log("com medo de Freeza.")
console.log("Dina ligou para Naruto dizendo que")

