console.log("Era uma vez...")
console.log("uma menina chamada Dina Fritz.")
console.log("Que caminhava pela estrada de tijolos amarelos.")
console.log("E um menino chamado Gohan.")
console.log("Gohan tinha cabelos espetados, mas não o lavava.")
console.log("Dina possuia cabelos dourados e olhos cinzas azulados.")
console.log("Eles viviam pacificamente dentro da Muralha Maria de tijolos de barro.")
console.log("com medo de Freeza.")
console.log("Dina ligou para Naruto dizendo que")
console.log("Quando um jovem chamado Naruto veio da vila da folha e lhes ensinaram a arte sábia ninja")
console.log("Onde o Kakashi ensinava os alunos a dança")
console.log("Mas encotrou o mestre Miagi e Daniel San treinando com")
console.log("Edivaldo Pericleiton Rasta, ao som do Cabeça de Gelo!")
